name: 'pr-validations'

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, edited, reopened]

permissions: read-all

jobs:
  pr-validations:
      name: 'PR Validation Checks'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Ensure label is present for PR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr view $PR_NUMBER --json labels --jq '.labels[0].name' > pr_label.txt

          pr_label=$(cat pr_label.txt)
          echo $pr_label
          
          match_found=0
          
          # Define an array of valid lables
          validlables=("Feature Introduced" "Fix" "Security Enhancement" "Deprecated")

          # Loop through each element of the array
          for validlable in "${validlables[@]}"
          do
            # Compare the current element with the string value
            if [ "$validlable" = "$pr_label" ]
            then
              echo "Found $pr_label in the array."
              match_found=1
              break
            fi
          done

          # If no match is found, echo a message
          if [ $match_found -eq 0 ]
          then
            echo "Please provide the valid label for your Pull Request"
            exit 1
          else
            echo "Label apply correctly."
          fi
